#!/usr/bin/env python3
"""
build_index.py -- Build SQLite FTS5 database from per-article markdown files.

Reads per-article files from docs/articles/ (generated by split_chapters.py),
creates a full-text search index with weighted columns, cross-reference table,
and context summaries for optimized retrieval.

Falls back to chapter-level files in docs/lisf_md/ and docs/cusf_md/ if
docs/articles/ does not exist.

Usage:
    python build_index.py

Output: docs/regulation.db
"""
import re
import sqlite3
import sys
import unicodedata
from pathlib import Path

PROJECT_DIR = Path(__file__).parent
ARTICLES_DIR = PROJECT_DIR / "docs" / "articles"
LISF_MD_DIR = PROJECT_DIR / "docs" / "lisf_md"
CUSF_MD_DIR = PROJECT_DIR / "docs" / "cusf_md"
DB_PATH = PROJECT_DIR / "docs" / "regulation.db"

# Patterns for splitting articles/dispositions (fallback mode)
LISF_SPLIT = re.compile(r"(\*\*ARTÍCULO\s+(\d+)\.?-\*\*)")
CUSF_SPLIT = re.compile(r"(\*\*DISPOSICIÓN\s+(\d+\.\d+\.\d+)\.?-\*\*)")
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)^---\s*\n", re.MULTILINE | re.DOTALL)


def parse_frontmatter(content: str) -> dict:
    """Extract YAML frontmatter fields."""
    fm = {}
    m = FRONTMATTER_RE.match(content)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                key, _, val = line.partition(":")
                fm[key.strip()] = val.strip()
    return fm


def normalize_keywords(keywords_str: str) -> str:
    """Normalize keywords: strip accents, lowercase, deduplicate."""
    normalized = unicodedata.normalize("NFD", keywords_str.lower())
    normalized = "".join(c for c in normalized if unicodedata.category(c) != "Mn")
    terms = [t.strip() for t in normalized.split(",")]
    return ", ".join(sorted(set(t for t in terms if t)))


def parse_list_field(value: str) -> list[str]:
    """Parse a frontmatter list field like '[item1, item2]'."""
    value = value.strip().strip("[]")
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


# =========================================================================
# Per-article mode (primary)
# =========================================================================

def process_article_files(articles_dir: Path) -> tuple[list[dict], list[dict]]:
    """Process per-article markdown files. Returns (article_rows, cross_ref_rows)."""
    rows = []
    xrefs = []

    if not articles_dir.is_dir():
        print(f"  Directory not found: {articles_dir}")
        return rows, xrefs

    for md_file in sorted(articles_dir.glob("*.md")):
        try:
            content = md_file.read_text(encoding="utf-8")
            fm = parse_frontmatter(content)

            law = fm.get("ley", "")
            number = fm.get("numero", "").strip('"')
            title = fm.get("titulo", "").strip('"')
            chapter = fm.get("capitulo", "").strip('"')
            keywords = normalize_keywords(fm.get("palabras_clave", ""))
            resumen = fm.get("resumen", "").strip('"')

            if not law or not number:
                print(f"  Skipping {md_file.name}: missing ley or numero")
                continue

            # Body text (strip frontmatter)
            body = FRONTMATTER_RE.sub("", content).strip()

            rows.append({
                "law": law,
                "number": number,
                "title": title,
                "chapter": chapter,
                "filename": md_file.name,
                "text": body[:30000],
                "keywords": keywords,
                "context_summary": resumen,
            })

            # Cross-references
            refs_internas = parse_list_field(fm.get("refs_internas", ""))
            refs_cruzadas = parse_list_field(fm.get("refs_cruzadas", ""))

            for ref in refs_internas:
                xrefs.append({
                    "from_law": law,
                    "from_number": number,
                    "to_law": law,
                    "to_number": ref,
                    "ref_type": "internal",
                })

            for ref in refs_cruzadas:
                if ":" in ref:
                    to_law, to_number = ref.split(":", 1)
                    xrefs.append({
                        "from_law": law,
                        "from_number": number,
                        "to_law": to_law,
                        "to_number": to_number,
                        "ref_type": f"{law}_to_{to_law}",
                    })

        except Exception as e:
            print(f"  Error processing {md_file.name}: {e}")
            continue

    return rows, xrefs


# =========================================================================
# Chapter-level fallback mode
# =========================================================================

def split_articles_fallback(content: str, pattern: re.Pattern) -> list[tuple[str, str]]:
    """Split content into (number, text) pairs by article/disposition markers."""
    markers = [(m.start(), m.group(2)) for m in pattern.finditer(content)]
    if not markers:
        return []
    articles = []
    for i, (pos, number) in enumerate(markers):
        end = markers[i + 1][0] if i + 1 < len(markers) else len(content)
        text = content[pos:end].strip()
        articles.append((number, text))
    return articles


def process_directory_fallback(source_dir: Path, law: str, pattern: re.Pattern) -> list[dict]:
    """Process chapter-level markdown files (fallback if docs/articles/ missing)."""
    rows = []
    if not source_dir.is_dir():
        return rows

    for md_file in sorted(source_dir.glob("*.md")):
        if md_file.name in ("00_indice.md", "full_lisf.md", "full_cusf.md"):
            continue
        try:
            content = md_file.read_text(encoding="utf-8")
            fm = parse_frontmatter(content)
            title = fm.get("titulo", md_file.stem)
            keywords = normalize_keywords(fm.get("palabras_clave", ""))

            articles = split_articles_fallback(content, pattern)
            if not articles:
                body = FRONTMATTER_RE.sub("", content).strip()
                if body and len(body) > 100:
                    rows.append({
                        "law": law,
                        "number": fm.get("disposiciones", md_file.stem),
                        "title": title,
                        "chapter": "",
                        "filename": md_file.name,
                        "text": body[:30000],
                        "keywords": keywords,
                        "context_summary": "",
                    })
            else:
                for number, text in articles:
                    rows.append({
                        "law": law,
                        "number": number,
                        "title": title,
                        "chapter": "",
                        "filename": md_file.name,
                        "text": text[:30000],
                        "keywords": keywords,
                        "context_summary": "",
                    })
        except Exception as e:
            print(f"  Error processing {md_file.name}: {e}")
    return rows


# =========================================================================
# Database builder
# =========================================================================

def build_database(rows: list[dict], xrefs: list[dict], db_path: Path):
    """Create SQLite database with FTS5 index and cross-reference table."""
    db_path.unlink(missing_ok=True)
    conn = sqlite3.connect(str(db_path))

    # Main articles table
    conn.execute("""
        CREATE TABLE articles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            law TEXT NOT NULL,
            number TEXT NOT NULL,
            title TEXT,
            chapter TEXT,
            filename TEXT NOT NULL,
            text TEXT NOT NULL,
            keywords TEXT,
            context_summary TEXT
        )
    """)

    # FTS5 virtual table with 5 columns for weighted BM25
    conn.execute("""
        CREATE VIRTUAL TABLE articles_fts USING fts5(
            number, title, text, keywords, context_summary,
            content='articles',
            content_rowid='id',
            tokenize='unicode61 remove_diacritics 2'
        )
    """)

    # Cross-reference table
    conn.execute("""
        CREATE TABLE cross_refs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            from_law TEXT NOT NULL,
            from_number TEXT NOT NULL,
            to_law TEXT NOT NULL,
            to_number TEXT NOT NULL,
            ref_type TEXT NOT NULL
        )
    """)

    # Insert articles
    for row in rows:
        conn.execute(
            "INSERT INTO articles (law, number, title, chapter, filename, text, keywords, context_summary) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (row["law"], row["number"], row["title"], row["chapter"],
             row["filename"], row["text"], row["keywords"], row["context_summary"]),
        )

    # Populate FTS index
    conn.execute("""
        INSERT INTO articles_fts (rowid, number, title, text, keywords, context_summary)
        SELECT id, number, title, text, keywords, context_summary FROM articles
    """)

    # Insert cross-references (deduplicated)
    seen = set()
    for xref in xrefs:
        key = (xref["from_law"], xref["from_number"], xref["to_law"], xref["to_number"])
        if key in seen:
            continue
        seen.add(key)
        conn.execute(
            "INSERT INTO cross_refs (from_law, from_number, to_law, to_number, ref_type) "
            "VALUES (?, ?, ?, ?, ?)",
            (xref["from_law"], xref["from_number"], xref["to_law"], xref["to_number"], xref["ref_type"]),
        )

    # Create indexes
    conn.execute("CREATE INDEX idx_law_number ON articles (law, number)")
    conn.execute("CREATE INDEX idx_chapter ON articles (law, chapter)")
    conn.execute("CREATE INDEX idx_filename ON articles (filename)")
    conn.execute("CREATE INDEX idx_xref_from ON cross_refs (from_law, from_number)")
    conn.execute("CREATE INDEX idx_xref_to ON cross_refs (to_law, to_number)")

    conn.commit()
    conn.close()


def main():
    print("Building regulation search index...\n")

    xrefs = []

    if ARTICLES_DIR.is_dir() and any(ARTICLES_DIR.glob("*.md")):
        # Primary mode: per-article files
        print(f"Using per-article files from {ARTICLES_DIR}")
        rows, xrefs = process_article_files(ARTICLES_DIR)
        lisf_count = sum(1 for r in rows if r["law"] == "lisf")
        cusf_count = sum(1 for r in rows if r["law"] == "cusf")
        print(f"  LISF: {lisf_count} articles")
        print(f"  CUSF: {cusf_count} dispositions")
    else:
        # Fallback: chapter-level files
        print("Per-article files not found. Using chapter-level files (fallback).")
        print(f"\nProcessing LISF ({LISF_MD_DIR})...")
        lisf_rows = process_directory_fallback(LISF_MD_DIR, "lisf", LISF_SPLIT)
        print(f"  Found {len(lisf_rows)} LISF articles")

        print(f"\nProcessing CUSF ({CUSF_MD_DIR})...")
        cusf_rows = process_directory_fallback(CUSF_MD_DIR, "cusf", CUSF_SPLIT)
        print(f"  Found {len(cusf_rows)} CUSF dispositions")

        rows = lisf_rows + cusf_rows

    print(f"\nTotal: {len(rows)} entries, {len(xrefs)} cross-references")

    print(f"\nBuilding database at {DB_PATH}...")
    build_database(rows, xrefs, DB_PATH)

    # Verify
    conn = sqlite3.connect(str(DB_PATH))
    count = conn.execute("SELECT COUNT(*) FROM articles").fetchone()[0]
    fts_count = conn.execute("SELECT COUNT(*) FROM articles_fts").fetchone()[0]
    xref_count = conn.execute("SELECT COUNT(*) FROM cross_refs").fetchone()[0]

    # Test weighted search
    results = conn.execute("""
        SELECT a.law, a.number, a.title
        FROM articles_fts f
        JOIN articles a ON a.id = f.rowid
        WHERE articles_fts MATCH 'reservas tecnicas'
        ORDER BY bm25(articles_fts, 0.0, 5.0, 1.0, 10.0, 8.0)
        LIMIT 5
    """).fetchall()

    print(f"\nDatabase built: {count} articles, {fts_count} FTS entries, {xref_count} cross-refs")
    print(f"File size: {DB_PATH.stat().st_size / 1024 / 1024:.1f} MB")

    print(f"\nTest search: 'reservas tecnicas'")
    for law, number, title in results:
        print(f"  [{law.upper()}] {number}: {title}")

    # Cross-ref stats
    xref_types = conn.execute(
        "SELECT ref_type, COUNT(*) FROM cross_refs GROUP BY ref_type"
    ).fetchall()
    print(f"\nCross-reference types:")
    for ref_type, cnt in xref_types:
        print(f"  {ref_type}: {cnt}")

    conn.close()
    print("\nDone!")


if __name__ == "__main__":
    main()
